blog/urls.py
from django.conf.urls import url

from . import views

app_name = 'blog'
urlpatterns = [
    # ex: /blog/
    url(r'^$', views.IndexView.as_view(), name='index'),
    # ex: /polls/5/
    #url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    # ex: /polls/5/results/
    #url(r'^(?P<pk>[0-9]+)/results/$', views.ResultsView.as_view(), name='results'),
    # ex: /polls/5/vote/
    #url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
    
    
    # ex: /polls/5/
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    # ex: /polls/5/vote/
    url(r'^(?P<blog_id>[0-9]+)/addComment/$', views.addComment, name='addComment'),
    # ex: /blog/archive
    url(r'^archive$', views.ArchiveView.as_view(), name="article"),
    # ex: /blog/about
    url(r'^about$', views.about, name='about'),
    # ex: /blog/tech_tips
    url(r'^tech_tips$', views.tech_tips, name='tech_tips'),
]

blog/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

from django.utils.encoding import python_2_unicode_compatible

# Create your models here.
@python_2_unicode_compatible
class Blog(models.Model):
    title_text = models.CharField(max_length=200)
    authors_name = models.CharField(max_length=50)
    content_text = models.CharField(max_length=2000)
    post_date = models.DateTimeField('date posted')
    
    def __str__(self):
        return self.title_text

@python_2_unicode_compatible        
class Comment(models.Model):
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE)
    comment_author = models.CharField(max_length=50)
    email = models.CharField(max_length=50)
    content_text = models.CharField(max_length=500)
    post_date = models.DateTimeField('date posted')
    
    def __str__(self):
        return self.content_text
    

blog/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import get_object_or_404,render
from django.views import generic
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse

from datetime import datetime

from .models import Blog, Comment

# Create your views here.
class IndexView(generic.ListView):
    template_name = 'blog/index.html'
    context_object_name = 'latest_blog_posts'
    
    def get_context_data(self, **kwargs):
        context = super(IndexView, self).get_context_data(**kwargs)
        context.update({
            'comment_list': Comment.objects.all(),
        })
        return context

    def get_queryset(self):
        """Return the last five published questions."""
        return Blog.objects.order_by('-post_date')[:3]
    
class ArchiveView(generic.ListView):
    template_name = 'blog/archive.html'
    context_object_name = 'all_blog_posts'
    
    def get_queryset(self):
        return Blog.objects.order_by('-post_date')
        
class DetailView(generic.DetailView):
    model = Blog
    template_name = 'blog/detail.html'
    
def addComment(request, blog_id):
    blog = get_object_or_404(Blog, pk=blog_id)
    try:
        comment_text = request.POST['content_text']
    except (KeyError, Comment.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'blog/detail.html', {
            'error_message': "There was en error creating the new comment.",
        })
    else:
        newComment = Comment(blog = blog, comment_author = 'author', email = 'email', content_text = comment_text, post_date = datetime.today())
        newComment.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('blog:detail', args=(blog.id,)))
    
def about(request):
    return render(request, 'blog/about.html')

def tech_tips(request):
    return render(request, 'blog/tech_tips.html')

blog/templates/blog/about.html
{% load static %}

<!DOCTYPE html>
<html>
    <head>
        <link rel="stylesheet" type="text/css" href="{% static 'blog/style.css' %}" />
        <title>About Me</title>
    </head>
    <body>
        <header>
            <nav>
              <ul>
                <li><a href="{% url 'blog:index'%}">Home</a></li>
                <li><a href="{% url 'blog:about'%}">About</a></li>
                <li><a href="{% url 'blog:tech_tips'%}">Tech Tips</a></li>
              </ul>
            </nav>
        </header>
        
        <h1>About Me</h1>
        
        <main>
            <img src="{% static 'blog/images/fry.jpg' %}" alt="fry looking back"/>
            <article>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse sed sollicitudin lacus. Curabitur quis tempor mi. 
                Proin vestibulum leo tellus, eu lacinia mauris consectetur non. Sed maximus nibh eget nunc euismod sollicitudin. 
                Aenean eu ullamcorper mi. Vivamus id cursus augue, eu bibendum turpis. Phasellus nec aliquet sapien. Ut pharetra ac dui sed gravida. 
                Quisque aliquet leo ullamcorper diam dignissim consequat. Ut ac eros a neque elementum condimentum quis quis metus. 
                Sed pretium quam nec velit ultrices, ac sodales lacus hendrerit. Maecenas ultricies feugiat velit, vestibulum dapibus leo tempus non.
            </article>
            
            <aside>
                <h1>Look at Me</h1>
                <img src="{% static 'blog/images/planet_express.jpg' %}" alt="planet express building"/>
                <img src="{% static 'blog/images/fry_fight.jpg' %}" alt="fry fighting zoidberg"/>
                <img src="{% static 'blog/images/bender_fry.jpg' %}" alt="bender and fry"/>
            </aside>
        </main>
        
        <footer>
            <span>&copy; 2017, Tyler Smith</span>
        </footer>
    </body>
</html>

blog/templates/blog/archive.html
{% load static %}

<!DOCTYPE html>
<html>
    <head>
        <link rel="stylesheet" type="text/css" href="{% static 'blog/style.css' %}" />
        <title>My Blog</title>
    </head>
    <body>
        <header>
            <nav>
              <ul>
                <li><a href="{% url 'blog:index'%}">Home</a></li>
                <li><a href="{% url 'blog:about'%}">About</a></li>
                <li><a href="{% url 'blog:tech_tips'%}">Tech Tips</a></li>
              </ul>
            </nav>
        </header>
    
        <main style="display:inline">
            {% for blog in all_blog_posts %}
                <article>
                    <h1>{{blog.title_text}}</h1>
                    {{blog.content_text|truncatewords:200}}
                    <span style="display:block">Comment Count: {{ blog.comment_set.count }}</span>
                </article>
            {% endfor %}
        </main>
    </body>
</html>

blog/templates/blog/detail.html
{% load static %}

<head>
    <link rel="stylesheet" type="text/css" href="{% static 'blog/style.css' %}" />
    <title>My Blog</title>
</head>
<body>
    <header>
        <nav>
          <ul>
            <li><a href="{% url 'blog:index'%}">Home</a></li>
            <li><a href="{% url 'blog:about'%}">About</a></li>
            <li><a href="{% url 'blog:tech_tips'%}">Tech Tips</a></li>
          </ul>
        </nav>
    </header>

    <main style="display:inline">
        <h1>{{ blog.title_text }}</h1>
        <article>{{ blog.content_text }}</article>
        
        <h3>comments</h3>
        <ul>
        {% for comment in blog.comment_set.all %}
            <li>{{ comment.content_text }} - {{ comment.comment_author }}</li>
        {% endfor%}
        </ul>
        
        <h3>Add comment</h3>
        <form action="{% url 'blog:addComment' blog.id %}" method="post">
        {% csrf_token %}
        <input type="textarea" name="content_text" id="content_text" />
        
        <input type="submit" value="Submit" />
        </form>
    </main>
</body>

blog/templates/blog/index.html
{% load static %}

<!DOCTYPE html>
<html>
    <head>
        <link rel="stylesheet" type="text/css" href="{% static 'blog/style.css' %}" />
        <title>My Blog</title>
    </head>
    <body>
        <header>
            <nav>
              <ul>
                <li><a href="{% url 'blog:index'%}">Home</a></li>
                <li><a href="{% url 'blog:about'%}">About</a></li>
                <li><a href="{% url 'blog:article'%}">Archive</a></li>
                <li><a href="{% url 'blog:tech_tips'%}">Tech Tips</a></li>
              </ul>
            </nav>
        </header>
        
        <h1>Philip J. Fry</h1>
        
        <main>
            {% if latest_blog_posts %}
                {% for blog in latest_blog_posts %}
                    <article>
                        <h1><a href= "{% url 'blog:detail' blog.id %}">{{blog.title_text}}</a></h1>
                        {{ blog.content_text|truncatewords:200 }}
                        <span style="display:block">Comment Count: {{ blog.comment_set.count }}</span>
                    </article>
                {% endfor %}
            {% else %}
                <article> no current blog posts </article>
            {% endif %}
            
            <aside>
                <a href="https://www.youtube.com/watch?v=iPUmE-tne5U">BEST SONG!!</a>
                <span style="display:block">Best Dog</span><img src="{% static 'blog/images/seymour.jpg' %}" alt="seymour the dog"/>
            </aside>
        </main>
        
        <footer>
            <span>&copy; 2017, Tyler Smith</span>
        </footer>
    </body>
</html>

blog/templates/blog/tech_tips.html
{% load static %}

<!DOCTYPE html>
<html>
    <head>
        <link rel="stylesheet" type="text/css" href="{% static 'blog/style.css' %}" />
        <title>Git Cheat Sheet</title>
    </head>
    <body>
        <header>
            <nav>
              <ul>
                <li><a href="{% url 'blog:index'%}">Home</a></li>
                <li><a href="{% url 'blog:about'%}">About</a></li>
                <li><a href="{% url 'blog:tech_tips'%}">Tech Tips</a></li>
              </ul>
            </nav>
        </header>
        
        <h1>Git Cheat Sheet</h1>
        <h2>For Dummies</h2>
        
        <main>
            <article class="tableflexbox">
                <div class="tableflexitem" style="order:3">
                    <h1>Git Info</h1>
                    <table class="tableimg3">
                        <tr>
                            <th>Name</th>
                            <th>Decription</th>
                            <th>Example</th>
                        </tr>
                        
                        <tr>
                            <td>Git Init</td>
                            <td>Creates a Git directory</td>
                            <td><code>Git Init</code></td>
                        </tr>
                        
                        <tr>
                            <td>Git Add <i>filename</i></td>
                            <td>Add changes to files to the git repository</td>
                            <td><code>Git Add index.html</code></td>
                        </tr>
                        
                        <tr>
                            <td>Git Status</td>
                            <td>Display the status of the repository</td>
                            <td><code>Git Status</code></td>
                        </tr>
                        
                        <tr>
                            <td>Git Commit</td>
                            <td>Commits changes from git add to the repository</td>
                            <td><code>Git Commit</code></td>
                        </tr>
                    </table>
                </div>
                
                <div class="tableflexitem" style="order:1">
                    <h1>HTML Info</h1>
                    <table class="tableimg1">
                        <tr>
                            <th>Name</th>
                            <th>Description</th>
                            <th>Example</th>
                        </tr>
                        <tr>
                            <td>html</td>
                            <td>tag containing all html code for the page.</td>
                            <td>&lt;html&gt;&lt;/html&gt;</td>
                        </tr>
                        <tr>
                            <td>head</td>
                            <td>tag containing info for how the page should interpert certain data.</td>
                            <td>&lt;head&gt;&lt;/head&gt;</td>
                        </tr>
                        <tr>
                            <td>a</td>
                            <td>tag for links to other pages or websites.</td>
                            <td>&lt;a href="www.google.com"&gt;&lt;/a&gt;</td>
                        </tr>
                        <tr>
                            <td>img</td>
                            <td>tag for displaying images.</td>
                            <td>&lt;img src="cow.jpg"/&gt;</td>
                        </tr>
                    </table>
                </div>
                
                <div class="tableflexitem" style="order:2">
                    <h1>CSS Info</h1>
                    <table class="tableimg2">
                        <tr>
                            <th>Name</th>
                            <th>Description</th>
                            <th>Example</th>
                        </tr>
                        <tr>
                            <td>height</td>
                            <td>set the height of an object can use px,percentage, and some others. percentage is based on parent object.</td>
                            <td>height: 100px;</td>
                        </tr>
                        <tr>
                            <td>width</td>
                            <td>set the width of an object can use px,percentage, and some others. percentage is based on parent object.</td>
                            <td>width: 70%</td>
                        </tr>
                        <tr>
                            <td>background-color</td>
                            <td>sets a background color</td>
                            <td>background-color: red;</td>
                        </tr>
                        <tr>
                            <td>background-image</td>
                            <td>sets a background image</td>
                            <td>background-image: url("cow.jpg");</td>
                        </tr>
                    </table>
                </div>
            </article>
        </main>
        
        <p>
            <a href="https://git-scm.com/docs/git-commit"><img src="{% static 'blog/images/git_logo.jpg' %}" alt="image missing"></a>
            <a href="https://git-scm.com/docs/git-commit">Better to look at git</a>
        </p>
        
        <footer>
            <span>&copy; 2017, Tyler Smith</span>
        </footer>
        
    </body>
</html>